In [2]:
import pandas as pd

In [4]:
countries_covid = pd.read_csv("Covid-19/countries-aggregated.csv")

In [5]:
countries_ref = pd.read_csv("Covid-19/reference.csv")

In [7]:
countries_ref.head()         #Data with missing values can be seen

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.93911,67.709953,Afghanistan,38928341.0
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.15330,20.168300,Albania,2877800.0
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.94990,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.03390,1.659600,Algeria,43851043.0
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.50630,1.521800,Andorra,77265.0

In [11]:
countries_ref             #Complete data which shows columns which have both missing and filled values

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.939110,67.709953,Afghanistan,38928341.0
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.153300,20.168300,Albania,2877800.0
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.949900,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.033900,1.659600,Algeria,43851043.0
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.506300,1.521800,Andorra,77265.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4311,84056037,US,USA,840.0,56037.0,Sweetwater,Wyoming,US,41.659439,-108.882788,"Sweetwater, Wyoming, US",42343.0
4312,84056039,US,USA,840.0,56039.0,Teton,Wyoming,US,43.935225,-110.589080,"Teton, Wyoming, US",23464.0
4313,84056041,US,USA,840.0,56041.0,Uinta,Wyoming,US,41.287818,-110.547578,"Uinta, Wyoming, US",20226.0
4314,84056043,US,USA,840.0,56043.0,Washakie,Wyoming,US,43.904516,-107.680187,"Washakie, Wyoming, US",7805.0
4315,84056045,US,USA,840.0,56045.0,Weston,Wyoming,US,43.839612,-104.567488,"Weston, Wyoming, US",6927.0

In [12]:
countries_ref_no_states = countries_ref[countries_ref["Province_State"].isna()]

In [13]:
countries_covid

              Date      Country  Confirmed  Recovered  Deaths
0       2020-01-22  Afghanistan          0          0       0
1       2020-01-23  Afghanistan          0          0       0
2       2020-01-24  Afghanistan          0          0       0
3       2020-01-25  Afghanistan          0          0       0
4       2020-01-26  Afghanistan          0          0       0
...            ...          ...        ...        ...     ...
161563  2022-04-12     Zimbabwe     247094          0    5460
161564  2022-04-13     Zimbabwe     247160          0    5460
161565  2022-04-14     Zimbabwe     247208          0    5462
161566  2022-04-15     Zimbabwe     247237          0    5462
161567  2022-04-16     Zimbabwe     247237          0    5462

[161568 rows x 5 columns]

In [14]:
countries_ref_no_states = countries_ref_no_states.rename(columns={"Country_Region": "Country"})

In [15]:
countries_ref_no_states

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.939110,67.709953,Afghanistan,3.892834e+07
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.153300,20.168300,Albania,2.877800e+06
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.949900,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.033900,1.659600,Algeria,4.385104e+07
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.506300,1.521800,Andorra,7.726500e+04
...,...,...,...,...,...,...,...,...,...,...,...,...
848,716,ZW,ZWE,716.0,NaN,NaN,NaN,Zimbabwe,-19.015438,29.154857,Zimbabwe,1.486293e+07
849,36,AU,AUS,36.0,NaN,NaN,NaN,Australia,-25.000000,133.000000,Australia,2.545970e+07
858,124,CA,CAN,124.0,NaN,NaN,NaN,Canada,60.000000,-95.000000,Canada,3.824611e+07
875,156,CN,CHN,156.0,NaN,NaN,NaN,China,35.861700,104.195450,China,1.411779e+09
910,840,US,USA,840.0,NaN,NaN,NaN,US,40.000000,-100.000000,US,3.294663e+08

In [16]:
countries_covid.merge(countries_ref_no_states[["Population", "Country"]])

              Date      Country  Confirmed  Recovered  Deaths  Population
0       2020-01-22  Afghanistan          0          0       0  38928341.0
1       2020-01-23  Afghanistan          0          0       0  38928341.0
2       2020-01-24  Afghanistan          0          0       0  38928341.0
3       2020-01-25  Afghanistan          0          0       0  38928341.0
4       2020-01-26  Afghanistan          0          0       0  38928341.0
...            ...          ...        ...        ...     ...         ...
161563  2022-04-12     Zimbabwe     247094          0    5460  14862927.0
161564  2022-04-13     Zimbabwe     247160          0    5460  14862927.0
161565  2022-04-14     Zimbabwe     247208          0    5462  14862927.0
161566  2022-04-15     Zimbabwe     247237          0    5462  14862927.0
161567  2022-04-16     Zimbabwe     247237          0    5462  14862927.0

[161568 rows x 6 columns]

In [17]:
countries_ref

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.939110,67.709953,Afghanistan,38928341.0
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.153300,20.168300,Albania,2877800.0
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.949900,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.033900,1.659600,Algeria,43851043.0
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.506300,1.521800,Andorra,77265.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4311,84056037,US,USA,840.0,56037.0,Sweetwater,Wyoming,US,41.659439,-108.882788,"Sweetwater, Wyoming, US",42343.0
4312,84056039,US,USA,840.0,56039.0,Teton,Wyoming,US,43.935225,-110.589080,"Teton, Wyoming, US",23464.0
4313,84056041,US,USA,840.0,56041.0,Uinta,Wyoming,US,41.287818,-110.547578,"Uinta, Wyoming, US",20226.0
4314,84056043,US,USA,840.0,56043.0,Washakie,Wyoming,US,43.904516,-107.680187,"Washakie, Wyoming, US",7805.0
4315,84056045,US,USA,840.0,56045.0,Weston,Wyoming,US,43.839612,-104.567488,"Weston, Wyoming, US",6927.0

In [18]:
countries_covid.merge(countries_ref[["Population", "Country_Region"]].rename(columns={"Country_Region": "Country"}))

               Date      Country  Confirmed  Recovered  Deaths  Population
0        2020-01-22  Afghanistan          0          0       0  38928341.0
1        2020-01-23  Afghanistan          0          0       0  38928341.0
2        2020-01-24  Afghanistan          0          0       0  38928341.0
3        2020-01-25  Afghanistan          0          0       0  38928341.0
4        2020-01-26  Afghanistan          0          0       0  38928341.0
...             ...          ...        ...        ...     ...         ...
3521035  2022-04-12     Zimbabwe     247094          0    5460  14862927.0
3521036  2022-04-13     Zimbabwe     247160          0    5460  14862927.0
3521037  2022-04-14     Zimbabwe     247208          0    5462  14862927.0
3521038  2022-04-15     Zimbabwe     247237          0    5462  14862927.0
3521039  2022-04-16     Zimbabwe     247237          0    5462  14862927.0

[3521040 rows x 6 columns]

In [22]:
countries_covid_sample = pd.read_csv("Covid-19/countries-aggregated-sample.csv")
countries_covid_sample

             Date      Country  Confirmed  Recovered  Deaths
0      2020-01-22  Afghanistan          0          0       0
1      2020-01-23  Afghanistan          0          0       0
2      2020-01-24  Afghanistan          0          0       0
3      2020-01-25  Afghanistan          0          0       0
4      2020-01-26  Afghanistan          0          0       0
...           ...          ...        ...        ...     ...
76812  2020-05-09       Kosovo        862        622      28
76813  2020-05-10       Kosovo        870        653      28
76814  2020-05-11       Kosovo        884        655      28
76815  2020-05-12       Kosovo        895        657      28
76816  2020-05-13       Kosovo        919        671      29

[76817 rows x 5 columns]

In [36]:
countries_refren = countries_ref.iloc[20:].rename(columns={"Country_Region": "Country"})

In [37]:
countries_covid_sampleNew = countries_covid_sample.merge(countries_refren, how="inner")
countries_covid_sampleNew

,Date,Country,Confirmed,Recovered,Deaths,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Lat,Long_,Combined_Key,Population
0,2020-01-22,Australia,0,0,0,36,AU,AUS,36.0,NaN,NaN,NaN,-25.000000,133.000000,Australia,25459700.0
1,2020-01-22,Australia,0,0,0,3601,AU,AUS,36.0,NaN,NaN,Australian Capital Territory,-35.473500,149.012400,"Australian Capital Territory, Australia",428100.0
2,2020-01-22,Australia,0,0,0,3602,AU,AUS,36.0,NaN,NaN,New South Wales,-33.868800,151.209300,"New South Wales, Australia",8118000.0
3,2020-01-22,Australia,0,0,0,3603,AU,AUS,36.0,NaN,NaN,Northern Territory,-12.463400,130.845600,"Northern Territory, Australia",245600.0
4,2020-01-22,Australia,0,0,0,3604,AU,AUS,36.0,NaN,NaN,Queensland,-27.469800,153.025100,"Queensland, Australia",5115500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293868,2020-05-09,Kosovo,862,622,28,383,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0
293869,2020-05-10,Kosovo,870,653,28,383,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0
293870,2020-05-11,Kosovo,884,655,28,383,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0
293871,2020-05-12,Kosovo,895,657,28,383,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0
293872,2020-05-13,Kosovo,919,671,29,383,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0

In [39]:
countries_covid_sampleNewL = countries_covid_sample.merge(countries_refren, how="left")
countries_covid_sampleNewL

,Date,Country,Confirmed,Recovered,Deaths,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Lat,Long_,Combined_Key,Population
0,2020-01-22,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-23,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-24,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-25,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-26,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306924,2020-05-09,Kosovo,862,622,28,383.0,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0
306925,2020-05-10,Kosovo,870,653,28,383.0,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0
306926,2020-05-11,Kosovo,884,655,28,383.0,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0
306927,2020-05-12,Kosovo,895,657,28,383.0,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0
306928,2020-05-13,Kosovo,919,671,29,383.0,XK,XKS,383.0,NaN,NaN,NaN,42.602636,20.902977,Kosovo,1810366.0

In [40]:
countries_covid_sampleNewR = countries_covid_sample.merge(countries_refren, how="right")
countries_covid_sampleNewR

,Date,Country,Confirmed,Recovered,Deaths,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Lat,Long_,Combined_Key,Population
0,2020-01-22,Belgium,0.0,0.0,0.0,5604,BE,BEL,56.0,NaN,NaN,Flemish Brabant,50.916700,4.583300,"Flemish Brabant, Belgium",1155843.0
1,2020-01-23,Belgium,0.0,0.0,0.0,5604,BE,BEL,56.0,NaN,NaN,Flemish Brabant,50.916700,4.583300,"Flemish Brabant, Belgium",1155843.0
2,2020-01-24,Belgium,0.0,0.0,0.0,5604,BE,BEL,56.0,NaN,NaN,Flemish Brabant,50.916700,4.583300,"Flemish Brabant, Belgium",1155843.0
3,2020-01-25,Belgium,0.0,0.0,0.0,5604,BE,BEL,56.0,NaN,NaN,Flemish Brabant,50.916700,4.583300,"Flemish Brabant, Belgium",1155843.0
4,2020-01-26,Belgium,0.0,0.0,0.0,5604,BE,BEL,56.0,NaN,NaN,Flemish Brabant,50.916700,4.583300,"Flemish Brabant, Belgium",1155843.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297803,NaN,US,NaN,NaN,NaN,84056037,US,USA,840.0,56037.0,Sweetwater,Wyoming,41.659439,-108.882788,"Sweetwater, Wyoming, US",42343.0
297804,NaN,US,NaN,NaN,NaN,84056039,US,USA,840.0,56039.0,Teton,Wyoming,43.935225,-110.589080,"Teton, Wyoming, US",23464.0
297805,NaN,US,NaN,NaN,NaN,84056041,US,USA,840.0,56041.0,Uinta,Wyoming,41.287818,-110.547578,"Uinta, Wyoming, US",20226.0
297806,NaN,US,NaN,NaN,NaN,84056043,US,USA,840.0,56043.0,Washakie,Wyoming,43.904516,-107.680187,"Washakie, Wyoming, US",7805.0
297807,NaN,US,NaN,NaN,NaN,84056045,US,USA,840.0,56045.0,Weston,Wyoming,43.839612,-104.567488,"Weston, Wyoming, US",6927.0

In [41]:
countries_covid_sampleNewO = countries_covid_sample.merge(countries_refren, how="outer")
countries_covid_sampleNewO

,Date,Country,Confirmed,Recovered,Deaths,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Lat,Long_,Combined_Key,Population
0,2020-01-22,Afghanistan,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-23,Afghanistan,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-24,Afghanistan,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-25,Afghanistan,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-26,Afghanistan,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310859,NaN,Western Sahara,NaN,NaN,NaN,732.0,EH,ESH,732.0,NaN,NaN,NaN,24.215500,-12.885800,Western Sahara,597330.0
310860,NaN,Winter Olympics 2022,NaN,NaN,NaN,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,39.904200,116.407400,Winter Olympics 2022,NaN
310861,NaN,Yemen,NaN,NaN,NaN,887.0,YE,YEM,887.0,NaN,NaN,NaN,15.552727,48.516388,Yemen,29825968.0
310862,NaN,Zambia,NaN,NaN,NaN,894.0,ZM,ZMB,894.0,NaN,NaN,NaN,-13.133897,27.849332,Zambia,18383956.0
310863,NaN,Zimbabwe,NaN,NaN,NaN,716.0,ZW,ZWE,716.0,NaN,NaN,NaN,-19.015438,29.154857,Zimbabwe,14862927.0

In [43]:
countries_covid_sampleNewA = countries_covid_sample.merge(countries_refren, how="left_anti")
countries_covid_sampleNewA

,Date,Country,Confirmed,Recovered,Deaths,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Lat,Long_,Combined_Key,Population
0,2020-01-22,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-23,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-24,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-25,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-26,Afghanistan,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,2022-04-12,Belarus,970750,0,6882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20396,2022-04-13,Belarus,971649,0,6885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20397,2022-04-14,Belarus,972448,0,6889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20398,2022-04-15,Belarus,973206,0,6894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20399,2022-04-16,Belarus,974046,0,6899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN