In [2]:
import pandas as pd

In [3]:
countries_covid_data = pd.read_csv("Covid-19/countries-aggregated.csv")    #to read a csv file

In [4]:
countries_covid_data.head()

         Date      Country  Confirmed  Recovered  Deaths
0  2020-01-22  Afghanistan          0          0       0
1  2020-01-23  Afghanistan          0          0       0
2  2020-01-24  Afghanistan          0          0       0
3  2020-01-25  Afghanistan          0          0       0
4  2020-01-26  Afghanistan          0          0       0

In [5]:
countries_covid_data.tail()

              Date   Country  Confirmed  Recovered  Deaths
161563  2022-04-12  Zimbabwe     247094          0    5460
161564  2022-04-13  Zimbabwe     247160          0    5460
161565  2022-04-14  Zimbabwe     247208          0    5462
161566  2022-04-15  Zimbabwe     247237          0    5462
161567  2022-04-16  Zimbabwe     247237          0    5462

In [6]:
countries_covid_data.info()                   #get information of a dataset

<class 'pandas.DataFrame'>
RangeIndex: 161568 entries, 0 to 161567
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       161568 non-null  str
 1   Country    161568 non-null  str
 2   Confirmed  161568 non-null  int64
 3   Recovered  161568 non-null  int64
 4   Deaths     161568 non-null  int64
dtypes: int64(3), str(2)
memory usage: 6.2 MB

In [7]:
countries_covid_data["Date"] = pd.to_datetime(countries_covid_data["Date"])

In [8]:
countries_covid_data["Date"].nunique()       #get total count of unique values in a column

816

In [9]:
countries_covid_data["Country"].nunique()

198

In [10]:
countries_covid_data.loc[161564]

Date         2022-04-13 00:00:00
Country                 Zimbabwe
Confirmed                 247160
Recovered                      0
Deaths                      5460
Name: 161564, dtype: object

In [13]:
type(countries_covid_data.loc[161564])            #each row is a series too

pandas.Series

In [15]:
countries_covid_data.set_index("Country")       #change the index of a DataFrame

                  Date  Confirmed  Recovered  Deaths
Country
Afghanistan 2020-01-22          0          0       0
Afghanistan 2020-01-23          0          0       0
Afghanistan 2020-01-24          0          0       0
Afghanistan 2020-01-25          0          0       0
Afghanistan 2020-01-26          0          0       0
...                ...        ...        ...     ...
Zimbabwe    2022-04-12     247094          0    5460
Zimbabwe    2022-04-13     247160          0    5460
Zimbabwe    2022-04-14     247208          0    5462
Zimbabwe    2022-04-15     247237          0    5462
Zimbabwe    2022-04-16     247237          0    5462

[161568 rows x 4 columns]

In [18]:
countries_covid_data.set_index("Country").loc[0]          #not an index anymore so loc not applicable

KeyError: 0

In [19]:
countries_covid_data.set_index("Country").loc["India"]  #now index is referred

              Date  Confirmed  Recovered  Deaths
Country
India   2020-01-22          0          0       0
India   2020-01-23          0          0       0
India   2020-01-24          0          0       0
India   2020-01-25          0          0       0
India   2020-01-26          0          0       0
...            ...        ...        ...     ...
India   2022-04-12   43038016          0  521736
India   2022-04-13   43039023          0  521737
India   2022-04-14   43039972          0  521743
India   2022-04-15   43040947          0  521747
India   2022-04-16   43042097          0  521751

[816 rows x 4 columns]

In [20]:
country_indexed_DF = countries_covid_data.set_index("Country")

In [21]:
country_indexed_DF

                  Date  Confirmed  Recovered  Deaths
Country
Afghanistan 2020-01-22          0          0       0
Afghanistan 2020-01-23          0          0       0
Afghanistan 2020-01-24          0          0       0
Afghanistan 2020-01-25          0          0       0
Afghanistan 2020-01-26          0          0       0
...                ...        ...        ...     ...
Zimbabwe    2022-04-12     247094          0    5460
Zimbabwe    2022-04-13     247160          0    5460
Zimbabwe    2022-04-14     247208          0    5462
Zimbabwe    2022-04-15     247237          0    5462
Zimbabwe    2022-04-16     247237          0    5462

[161568 rows x 4 columns]

In [22]:
country_indexed_DF["Country"]     #index can't be selected like a normal column

KeyError: 'Country'

In [24]:
country_indexed_DF.reset_index()        #reset index to solve previous problem

            Country       Date  Confirmed  Recovered  Deaths
0       Afghanistan 2020-01-22          0          0       0
1       Afghanistan 2020-01-23          0          0       0
2       Afghanistan 2020-01-24          0          0       0
3       Afghanistan 2020-01-25          0          0       0
4       Afghanistan 2020-01-26          0          0       0
...             ...        ...        ...        ...     ...
161563     Zimbabwe 2022-04-12     247094          0    5460
161564     Zimbabwe 2022-04-13     247160          0    5460
161565     Zimbabwe 2022-04-14     247208          0    5462
161566     Zimbabwe 2022-04-15     247237          0    5462
161567     Zimbabwe 2022-04-16     247237          0    5462

[161568 rows x 5 columns]

In [27]:
country_indexed_DF.iloc[161564]   #get number based row even in a changed index Dataframe

Date         2022-04-13 00:00:00
Confirmed                 247160
Recovered                      0
Deaths                      5460
Name: Zimbabwe, dtype: object

In [29]:
covid19_zimbabwe = countries_covid_data.query("(Country == 'Zimbabwe')")

In [31]:
covid19_zimbabwe                   #indices still start from default assigned numbers

             Date   Country  Confirmed  Recovered  Deaths
160752 2020-01-22  Zimbabwe          0          0       0
160753 2020-01-23  Zimbabwe          0          0       0
160754 2020-01-24  Zimbabwe          0          0       0
160755 2020-01-25  Zimbabwe          0          0       0
160756 2020-01-26  Zimbabwe          0          0       0
...           ...       ...        ...        ...     ...
161563 2022-04-12  Zimbabwe     247094          0    5460
161564 2022-04-13  Zimbabwe     247160          0    5460
161565 2022-04-14  Zimbabwe     247208          0    5462
161566 2022-04-15  Zimbabwe     247237          0    5462
161567 2022-04-16  Zimbabwe     247237          0    5462

[816 rows x 5 columns]

In [32]:
covid19_zimbabwe.loc[0]         #index not matched

KeyError: 0

In [34]:
covid19_zimbabwe.iloc[0]        #always does location based searching not index based

Date         2020-01-22 00:00:00
Country                 Zimbabwe
Confirmed                      0
Recovered                      0
Deaths                         0
Name: 160752, dtype: object

In [37]:
countries_covid_data["Country"] == "India"     #boolean series evaluation for Country == India

0         False
1         False
2         False
3         False
4         False
          ...
161563    False
161564    False
161565    False
161566    False
161567    False
Name: Country, Length: 161568, dtype: bool

In [38]:
countries_covid_data["Date"] == "2020-06-22"    #boolean series evaluation for Date 22 June 2020

0         False
1         False
2         False
3         False
4         False
          ...
161563    False
161564    False
161565    False
161566    False
161567    False
Name: Date, Length: 161568, dtype: bool

In [43]:
#Boolean series Data for Country: India on date 22 June 2020
mask = (countries_covid_data["Country"] == "India") & (countries_covid_data["Date"] == "2020-06-22")
mask

0         False
1         False
2         False
3         False
4         False
          ...
161563    False
161564    False
161565    False
161566    False
161567    False
Length: 161568, dtype: bool

In [42]:
countries_covid_data[mask]   #fetch data for the created mask directly by referring it just like columns

            Date Country  Confirmed  Recovered  Deaths
65432 2020-06-22   India     440215     248190   14011

In [44]:
#direct selection to display data
countries_covid_data[(countries_covid_data["Country"] == "India") & (countries_covid_data["Date"] == "2020-06-22")]

            Date Country  Confirmed  Recovered  Deaths
65432 2020-06-22   India     440215     248190   14011

In [85]:
#querying method to mask for newer Pandas versions
countries_covid_data.query("(Country == 'Zimbabwe') & (Date == '2021-06-22')") 
#Didn't output when date was of type datetime

Empty DataFrame
Columns: [Date, Country, Confirmed, Recovered, Deaths]
Index: []

In [67]:
countries_covid_data["Date"]

0        2020-01-22
1        2020-01-23
2        2020-01-24
3        2020-01-25
4        2020-01-26
            ...
161563   2022-04-12
161564   2022-04-13
161565   2022-04-14
161566   2022-04-15
161567   2022-04-16
Name: Date, Length: 161568, dtype: datetime64[us]

In [87]:
countries_covid_data["Date"] = (countries_covid_data["Date"]).astype(str)  #convert date from datetime to string type

In [88]:
countries_covid_data.query("(Country == 'India') & (Date == '2020-06-22')")  #output when Date converted to string

             Date Country  Confirmed  Recovered  Deaths
65432  2020-06-22   India     440215     248190   14011